
# site domain
url: https://www.lib.uidaho.edu

# url to production objects store
digital-objects: https://collectionbuilder.sfo2.cdn.digitaloceanspaces.com/moscon_programs_collection

exclude: [docs/, Rakefile, README.md, LICENSE, objects/]
