
# site domain
url: https://www.lib.uidaho.edu

# url to production objects store
digital-objects: https://lchs.sfo2.cdn.digitaloceanspaces.com

exclude: [docs/, Rakefile, README.md, LICENSE, objects/, scripts/, Dockerfile, docker-compose*.yml]
