version: '2.4'
services:
  collectionbuilder:
    build: .
    env_file: .env
    environment:
      JEKYLL_ENV: development
    volumes:
      - .:/app
    ports:
      - 4000:4000
    network_mode: host
    command: ["s", "-H", "0.0.0.0", "-P", "4001", "--config=_config.yml"]

  #   links:
  #     - elasticsearch
  # elasticsearch:
  #   image: elasticsearch:7.4.2
  #   environment:
  #   - discovery.type=single-node
